language: java
sudo: required

env:
  matrix:
  - OS_TYPE=centos OS_VERSION=7

services:
  - docker

before_install:
  - cd project
  - docker pull centos:7
  #download setenv.sh and dockerfile1
  - curl -J -O --insecure https://drive.fds.vn/index.php/s/NzWbGDaFNNrvoc9/download 
  - chmod +x setenv.sh
  - curl -J -O --insecure https://drive.fds.vn/index.php/s/vO0TwCEXA6WPI5M/download
  #Create Eviroment Docker Image
  - docker build -t "opencps:enviroment" -f dockerfile1 .
  
  #download build.sh
  - curl -J -O --insecure https://drive.fds.vn/index.php/s/s5RZczUPRLh572O/download
  - chmod +x build.sh
  - curl -J -O --insecure https://drive.fds.vn/index.php/s/qHyShIKDzaRrdvZ/download
 
script:
  #Create Build Docker Image
  - docker build -t "opencps:build" -f dockerfile2 .

  
notifications:
  email: false
