language: java
sudo: required

env:
  matrix:
  - OS_TYPE=centos OS_VERSION=7

services:
  - docker

before_install: 
  - docker pull centos:7
  #download setenv.sh
  - curl -J -O --insecure https://drive.fds.vn/index.php/s/NzWbGDaFNNrvoc9/download
  #download build.sh
  - curl -J -O --insecure https://drive.fds.vn/index.php/s/s5RZczUPRLh572O/download
  #Create Eviroment Docker Image
  - docker build -t "opencps:enviroment" - < dockerfile1
  #Create Build Docker Image
 
script:
  - docker build -t "opencps:build" - < dockerfile2

  
notifications:
  email: false
